server:
  port: 8000

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-routes
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
            - id: auth-routes
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
          discovery:
            locator:
              enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}


jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRED}


gateway:
  public-paths:
    - /api/v1/auth/signup
    - /api/v1/auth/login
    - /actuator/health
