spring:
  application:
    name: queue-service

  data:
    redis:
      host: localhost # Docker 환경이라면 컨테이너 이름 또는 IP
      port: 6380

  datasource:
    url: jdbc:postgresql://localhost:15432/rushdeal_db
    username: rushdeal
    password: rushdeal
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: queue_schema
        format_sql: true
        use_sql_comments: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    appname: queue-service

server:
  port: 8011