description = 'Auth Service for rush-deal Project'

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// eureka
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

	// database
	runtimeOnly 'org.postgresql:postgresql'

	// jpa
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	testImplementation 'org.springframework.security:spring-security-test'

	// validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// feign client
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

	// Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// Jackson for JSON serialization
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

	// jjwt
	implementation 'io.jsonwebtoken:jjwt-api:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.13.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.13.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
